### ISSUE TITLE
feat: delete - charts provided in an armada yaml

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#33]
As we can deploy multiple charts at once, we should be able to mark charts for delete or delete all charts in the yaml.

Functionality will delete charts that are no longer in the Release. They will not be in the armada yaml. Armada should identify the chart that is missing from the declaration, and remove it.

**Comment by g0r1v3r4** [comment]
Is Armada.yaml a complete/unique source of truth?

Will the Armada.yaml have a unique Release only?

Can there be two Armada.yaml each with different releases?

**Comment by gardlt** [comment]
- yes the armada yaml will be a the source of truth
- yes, so because of the way we are doing thing we don't currently have  a check in for unique, but in this issue, we will need to make sure that every `chart` has a unique `release_name` against the tiller service
- yes.

**Comment by g0r1v3r4** [comment]
why a unique release_name - maybe all you need is UUID type variable.
why is the release_name meant to be unique? is that something that Kubernetes or Helm searches for?
Basically, maybe the release_name does not need to be unique if you have a UUID variable.

Is the working idea that you will:
Check release_name for uniqueness across the file repository structure of all Armada.yaml
since the relationship between release_name and a list of chart - is that you will need a past and a present
because you are comparing a chart list that differs somehow - in which you remove the charts that are no longer present

Is this the right idea?

**Comment by gardlt** [comment]
this is how the kubernetes/helm project developed the tiller service. the helm client does check for this, but we are not using it.
